<?php

namespace Database\Seeders;

use App\Models\Microsite;
use App\Models\Place;
use App\Models\Review;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            [
                'name' => 'Es Dawet Pak Min',
                'slug' => 'es-dawet-pak-min',
                'category' => 'es-dawet',
                'tagline' => 'Legend sejak 2001, santan gurih + gula Jawa asli',
                'description' => 'Es dawet legendaris yang tak pernah sepi pembeli. Santan gurih dipadu gula Jawa asli, dawetnya kenyal lembut. Porsi pas, harga ramah kantong.',
                'address' => 'Jl. Kalingga, Magelang (dekat Pasar Taruma Negara)',
                'latitude' => -7.4845000,
                'longitude' => 110.2148000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '10:00',
                'close_time' => null,
                'price_range' => 'Mulai Rp5.000',
                'tips' => 'Datang sebelum jam 15.00 sebelum habis',
                'since_year' => 2001,
                'is_legendary' => true,
                'is_featured' => true,
                'image' => '/img/places/dawet.svg',
                'views' => 4320,
                'reviews' => [
                    ['name' => 'Rina', 'rating' => 5, 'comment' => 'Dawetnya juara, gula jawanya asli. Wajib coba!', 'approved' => true],
                    ['name' => 'Budi', 'rating' => 5, 'comment' => 'Legend banget, dari kecil sampai sekarang rasanya konsisten.', 'approved' => true],
                    ['name' => 'Ani', 'rating' => 4, 'comment' => 'Enak, cuma antreannya lumayan.', 'approved' => false],
                ],
            ],
            [
                'name' => 'Bakso Pak Iwan',
                'slug' => 'bakso-pak-iwan',
                'category' => 'bakso',
                'tagline' => 'Hampir 20 tahun, porsi melimpah, kuah konsisten',
                'description' => 'Bakso dengan porsi melimpah dan kuah yang konsisten sejak dulu. Cocok untuk yang ingin kenyang dengan harga bersahabat.',
                'address' => 'Jl. Kapten Yahya (depan TKIT Asy Syaffa\')',
                'latitude' => -7.4720000,
                'longitude' => 110.2120000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '10:30',
                'close_time' => '17:30',
                'price_range' => 'Rp10.000 - Rp18.000',
                'tips' => 'Minta bakso urat kalau suka tekstur kenyal',
                'since_year' => 2006,
                'is_legendary' => true,
                'is_featured' => true,
                'image' => '/img/places/bakso.svg',
                'views' => 3850,
                'reviews' => [
                    ['name' => 'Dewi', 'rating' => 5, 'comment' => 'Kuahnya gurih banget, porsinya banyak.', 'approved' => true],
                ],
            ],
            [
                'name' => 'Bakso Krikil Mas Kentung',
                'slug' => 'bakso-krikil-mas-kentung',
                'category' => 'bakso',
                'tagline' => 'Satu mangkok bisa sampai 60 butir bakso krikil',
                'description' => 'Bakso krikil kecil-kecil yang bisa sampai 60 butir semangkok. Sejak 2016 dan selalu rame setiap hari.',
                'address' => 'Jl. Pemuda, Magelang Tengah',
                'latitude' => -7.4690000,
                'longitude' => 110.2160000,
                'whatsapp' => '6281234567890',
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '11:00',
                'close_time' => '20:00',
                'price_range' => 'Mulai Rp8.000',
                'tips' => 'Coba level pedas 2, pas di lidah',
                'since_year' => 2016,
                'is_legendary' => false,
                'is_featured' => true,
                'image' => '/img/places/bakso.svg',
                'views' => 5210,
                'microsite' => [
                    'hero_title' => 'Bakso Krikil Mas Kentung',
                    'hero_image' => '/img/places/bakso.svg',
                    'about' => 'Bakso krikil legendaris Magelang sejak 2016. Satu mangkok bisa berisi hingga 60 butir bakso kecil yang kenyal. Selalu rame, selalu bikin kangen.',
                    'menu' => [
                        ['name' => 'Bakso Krikil Spesial', 'desc' => '60 butir bakso krikil + mie + kuah gurih', 'price' => 'Rp15.000'],
                        ['name' => 'Bakso Krikil Jumbo', 'desc' => '30 butir + 1 bakso jumbo di tengah', 'price' => 'Rp18.000'],
                        ['name' => 'Bakso Krikil Original', 'desc' => '40 butir bakso krikil klasik', 'price' => 'Rp8.000'],
                        ['name' => 'Es Teh Manis', 'desc' => 'Pelepas dahaga', 'price' => 'Rp3.000'],
                    ],
                    'gallery' => ['/img/places/bakso.svg', '/img/hero.svg'],
                    'socials' => ['instagram' => 'https://www.instagram.com/', 'whatsapp' => '6281234567890'],
                    'map_embed' => null,
                    'accent_color' => '#c0392b',
                    'cta_text' => 'Pesan via WhatsApp',
                    'is_active' => true,
                ],
                'reviews' => [
                    ['name' => 'Joko', 'rating' => 5, 'comment' => 'Hitung sendiri, beneran 60 butir!', 'approved' => true],
                    ['name' => 'Sari', 'rating' => 4, 'comment' => 'Enak dan rame, tapi antre pas jam makan siang.', 'approved' => true],
                ],
            ],
            [
                'name' => 'Martabak Sahabat',
                'slug' => 'martabak-sahabat',
                'category' => 'martabak',
                'tagline' => 'Legend sejak tahun 2000',
                'description' => 'Martabak legendaris yang menemani Magelang sejak tahun 2000. Isi tebal, manisnya pas, cocok untuk malam minggu.',
                'address' => 'Jl. Ikhlas, Magersari, Magelang Selatan',
                'latitude' => -7.4900000,
                'longitude' => 110.2120000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '16:00',
                'close_time' => '21:30',
                'price_range' => 'Mulai Rp18.000',
                'tips' => 'Pesan martabak coklat-keju, signature-nya',
                'since_year' => 2000,
                'is_legendary' => true,
                'is_featured' => true,
                'image' => '/img/places/martabak.svg',
                'views' => 2980,
                'reviews' => [
                    ['name' => 'Yoga', 'rating' => 5, 'comment' => 'Martabak terbaik Magelang, dari dulu sampai sekarang.', 'approved' => true],
                ],
            ],
            [
                'name' => 'Kopi Jos Pak Siswanto',
                'slug' => 'kopi-jos-pak-siswanto',
                'category' => 'kopi-wedang',
                'tagline' => 'Kopi klasik dibakar arang, khas Alun-alun Magelang',
                'description' => 'Pelopor kopi jos Magelang. Kopi panas disiram bara arang hingga berbuih — sensasi hangat yang khas, ditemani wedang ronde di malam hari.',
                'address' => 'Alun-alun Selatan, Magelang Tengah',
                'latitude' => -7.4740000,
                'longitude' => 110.2170000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '17:00',
                'close_time' => '23:00',
                'price_range' => 'Rp5.000 - Rp15.000',
                'tips' => 'Datang malam hari, suasana alun-alun paling hidup',
                'since_year' => 1998,
                'is_legendary' => true,
                'is_featured' => true,
                'image' => '/img/places/kopi.svg',
                'views' => 4640,
                'microsite' => [
                    'hero_title' => 'Kopi Jos Pak Siswanto',
                    'hero_image' => '/img/places/kopi.svg',
                    'about' => 'Kopi jos legendaris di Alun-alun Magelang sejak 1998. Kopi klasik yang dibakar dengan arang, plus wedang ronde dan aneka minuman hangat.',
                    'menu' => [
                        ['name' => 'Kopi Jos', 'desc' => 'Kopi panas + bara arang, klasik', 'price' => 'Rp7.000'],
                        ['name' => 'Wedang Ronde', 'desc' => 'Ronde kenyal, kuah jahe hangat', 'price' => 'Rp8.000'],
                        ['name' => 'Kopi Susu', 'desc' => 'Kopi + susu kental manis', 'price' => 'Rp10.000'],
                        ['name' => 'Roti Bakar', 'desc' => 'Roti bakar coklat keju', 'price' => 'Rp12.000'],
                    ],
                    'gallery' => ['/img/places/kopi.svg', '/img/hero.svg'],
                    'socials' => ['instagram' => 'https://www.instagram.com/'],
                    'map_embed' => null,
                    'accent_color' => '#8d5a1f',
                    'cta_text' => 'Hubungi Kami',
                    'is_active' => true,
                ],
                'reviews' => [
                    ['name' => 'Agus', 'rating' => 5, 'comment' => 'Khas banget, kopi jos wajib dicoba tiap ke Magelang.', 'approved' => true],
                    ['name' => 'Maya', 'rating' => 4, 'comment' => 'Wedang rondenya enak, hangat di perut.', 'approved' => false],
                ],
            ],
            [
                'name' => 'Wedang Ronde Alun-Alun',
                'slug' => 'wedang-ronde-alun-alun',
                'category' => 'kopi-wedang',
                'tagline' => 'Hangatnya jahe, kenyalnya ronde',
                'description' => 'Wedang ronde tradisional yang disajikan hangat dengan kuah jahe manis. Tempat nongkrong favorit warga Magelang di malam hari.',
                'address' => 'Alun-alun Magelang, sisi timur',
                'latitude' => -7.4730000,
                'longitude' => 110.2180000,
                'whatsapp' => null,
                'open_days' => 'Fri,Sat,Sun',
                'open_time' => '18:00',
                'close_time' => '22:00',
                'price_range' => 'Mulai Rp7.000',
                'tips' => 'Paling rame Jumat malam',
                'since_year' => 2005,
                'is_legendary' => false,
                'is_featured' => false,
                'image' => '/img/places/kopi.svg',
                'views' => 1740,
                'reviews' => [],
            ],
            [
                'name' => 'Nasi Goreng Magelangan Bu Lurah',
                'slug' => 'nasi-goreng-magelangan-bu-lurah',
                'category' => 'nasi-goreng-magelangan',
                'tagline' => 'Nasi goreng khas Magelangan, gurih & kaya isi',
                'description' => 'Nasi goreng Magelangan otentik dengan campuran mie, ayam suwir, telur, dan bumbu khas yang gurih. Seporsi mengenyangkan.',
                'address' => 'Jl. Pahlawan, Magelang',
                'latitude' => -7.4660000,
                'longitude' => 110.2150000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '17:00',
                'close_time' => '23:00',
                'price_range' => 'Rp12.000 - Rp20.000',
                'tips' => 'Tambah telur ceplok biar makin mantap',
                'since_year' => 2010,
                'is_legendary' => false,
                'is_featured' => true,
                'image' => '/img/places/nasgor.svg',
                'views' => 2210,
                'reviews' => [
                    ['name' => 'Putri', 'rating' => 4, 'comment' => 'Gurih, porsinya pas buat laper tingkat tinggi.', 'approved' => true],
                ],
            ],
            [
                'name' => 'Mie Ayam Bakso Bu Tarmi',
                'slug' => 'mie-ayam-bakso-bu-tarmi',
                'category' => 'street-food',
                'tagline' => 'Mie ayam paket komplit dengan bakso',
                'description' => 'Mie ayam gurih dengan topping melimpah plus bakso kenyal. Satu porsi bisa buat makan dua orang.',
                'address' => 'Jl. A. Yani, Magelang',
                'latitude' => -7.4710000,
                'longitude' => 110.2180000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '08:00',
                'close_time' => '15:00',
                'price_range' => 'Rp10.000 - Rp15.000',
                'tips' => 'Datang sebelum jam 12 siang, porsi paling fresh',
                'since_year' => 2012,
                'is_legendary' => false,
                'is_featured' => false,
                'image' => '/img/places/street.svg',
                'views' => 1890,
                'reviews' => [],
            ],
            [
                'name' => 'Getuk Goreng Bu Tini',
                'slug' => 'getuk-goreng-bu-tini',
                'category' => 'street-food',
                'tagline' => 'Oleh-oleh khas Magelang, getuk goreng manis',
                'description' => 'Getuk goreng khas Magelang dengan tekstur lembut dan rasa manis gurih. Jajanan pasar yang selalu ludes dibawa pulang.',
                'address' => 'Jl. Tidar, Magelang Selatan',
                'latitude' => -7.4850000,
                'longitude' => 110.2100000,
                'whatsapp' => '6285712345678',
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                'open_time' => '06:00',
                'close_time' => '16:00',
                'price_range' => 'Rp5.000 - Rp15.000',
                'tips' => 'Beli getuk anget langsung dari penggorengan',
                'since_year' => 2008,
                'is_legendary' => false,
                'is_featured' => true,
                'image' => '/img/places/street.svg',
                'views' => 1560,
                'reviews' => [],
            ],
            [
                'name' => 'Soto Ayam Pak Salim',
                'slug' => 'soto-ayam-pak-salim',
                'category' => 'street-food',
                'tagline' => 'Kuah kuning bening, suwiran ayam melimpah',
                'description' => 'Soto ayam kampung dengan kuah kuning gurih, suwiran ayam banyak, plus sambal yang nendang. Sarapan favorit warga sekitar.',
                'address' => 'Jl. Veteran, Magelang',
                'latitude' => -7.4760000,
                'longitude' => 110.2130000,
                'whatsapp' => null,
                'open_days' => 'Mon,Tue,Wed,Thu,Fri,Sat',
                'open_time' => '07:00',
                'close_time' => '12:00',
                'price_range' => 'Rp10.000 - Rp15.000',
                'tips' => 'Datang pagi buta, kuah masih seger',
                'since_year' => 2003,
                'is_legendary' => false,
                'is_featured' => false,
                'image' => '/img/places/street.svg',
                'views' => 1340,
                'reviews' => [],
            ],
        ];

        foreach ($places as $data) {
            $category = \App\Models\Category::where('slug', $data['category'])->first();

            $reviews = $data['reviews'];
            $microsite = $data['microsite'] ?? null;
            unset($data['category'], $data['reviews'], $data['microsite']);

            $place = Place::firstOrCreate(['slug' => $data['slug']], array_merge($data, ['category_id' => $category->id]));

            foreach ($reviews as $review) {
                Review::firstOrCreate(
                    ['place_id' => $place->id, 'name' => $review['name'], 'comment' => $review['comment']],
                    [
                        'rating' => $review['rating'],
                        'is_approved' => $review['approved'],
                    ]
                );
            }

            if ($microsite) {
                Microsite::firstOrCreate(
                    ['place_id' => $place->id],
                    $microsite
                );
            }
        }
    }
}
